dist: xenial  # required to run 3.7+
language: python
sudo: true
python:
  - "3.5"
  - "3.6"
  - "3.7"
sudo: false
install:
  - cd src
  - pip install -U pip setuptools wheel codecov coverage
  - pip install -Ue .
script:
  - bash ../.travis.sh $JOB
cache:
  directories:
    - $HOME/.cache/pip
services:
  - postgresql
env:
  - JOB=tests
  - JOB=style
  - JOB=docs
addons:
  postgresql: "9.6"
